### ISSUE TITLE
How to setup Matrix webhook in Element ?

### ISSUE THREAD

**Issue by ghost** [chriswep/kanboard-plugin-matrix#1]
Hi, 
I'm trying to use the Matrix plugin in Kanboard. However, I could not find any setting in Element for desktop (a PC Matrix client) to get the webhook URL required.
Is there a way to get this URL somewhere ? Are there other clients that allow that ?
Thanks !

**Comment by chriswep** [comment]
Hi, you need a use a separate appservice on your self hosted matrix-server to use webhooks. This plugin is tested with https://github.com/turt2live/matrix-appservice-webhooks - it's old, but it still works.

**Comment by ghost** [comment]
Hi, thanks a lot for your reply. I naively
        thought all Synapse servers allowed it... I'm not using any self
        hosted matrix server for now, so I'll stick with email
        notifications.
    
    Le 27/01/2022 à 09:53, Chris a écrit :
    
    
      
      Hi, you need a use a separate appservice on your
        self hosted matrix-server to use webhooks. This plugin is tested
        with https://github.com/turt2live/matrix-appservice-webhooks
        - it's old, but it still works.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/chriswep/kanboard-plugin-matrix/issues/1#issuecomment-1022981701",
"url": "https://github.com/chriswep/kanboard-plugin-matrix/issues/1#issuecomment-1022981701",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
