### ISSUE TITLE
Other messangers

### ISSUE THREAD

**Issue by charly1080** [chriswep/kanboard-plugin-matrix#2]
If I understood your plugin correctly, the notifications from Kanboard come to the messanger matrix instead of by mail.

Would it also be possible to control other messangers like Whatsapp, Threema and/or Signal?

**Comment by chriswep** [comment]
As long as the desired communication service has an API / bridge to send messages to, it is possible. However you have to write a separate plugin for that. I suggest looking for a plug-in that is most similar to what you want and fork from there.
